let allOrders=[],filter="all",menuData=null;
const $=s=>document.querySelector(s),money=n=>(Number(n)||0).toFixed(2)+" ر.س";
async function api(path,opt={}){const r=await fetch("/api"+path,{headers:{"content-type":"application/json",...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"حدث خطأ");return d}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$("#"+id).classList.remove("hidden");document.querySelectorAll(".side").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="orders")loadOrders();if(id==="menu")loadMenu();if(id==="zones")loadZones();if(id==="coupons")loadCoupons()}
document.querySelectorAll(".side").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$("#menuBtn").onclick=()=>document.querySelector(".layout").classList.toggle("open");
$("#loginBtn").onclick=async()=>{try{await api("/admin/login",{method:"POST",body:JSON.stringify({password:$("#pass").value})});$("#login").classList.add("hidden");$("#app").classList.remove("hidden");loadAll()}catch(e){$("#loginMsg").textContent=e.message}};
$("#pass").onkeydown=e=>{if(e.key==="Enter")$("#loginBtn").click()};
$("#logout").onclick=async()=>{await api("/admin/logout",{method:"POST"});location.reload()};
function statusName(s){return {new:"جديد",accepted:"تم القبول",preparing:"قيد التجهيز",ready:"جاهز",out_for_delivery:"جاري التوصيل",completed:"مكتمل",cancelled:"ملغي"}[s]||s}
function orderCard(o){return `<div class="order"><div class="orderNo">#${o.order_no}</div><div class="orderInfo"><b>${esc(o.customer_name)} — ${esc(o.phone)}</b>${esc(o.zone_name||"استلام/بدون منطقة")}<br>${o.items.map(i=>esc(i.name)+" × "+i.qty).join("، ")}<br><strong>${money(o.total)}</strong></div><select class="status ${o.status}" onchange="setStatus(${o.id},this.value)">${["new","accepted","preparing","ready","out_for_delivery","completed","cancelled"].map(s=>`<option value="${s}" ${s===o.status?"selected":""}>${statusName(s)}</option>`).join("")}</select></div>`}
function esc(x){return String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function loadOrders(){try{allOrders=await api("/admin/orders");const arr=filter==="all"?allOrders:allOrders.filter(o=>o.status===filter);$("#ordersList").innerHTML=arr.length?arr.map(orderCard).join(""):'<div class="panel">لا توجد طلبات.</div>';$("#dashOrders").innerHTML=allOrders.slice(0,5).map(orderCard).join("")||'<div class="panel">لا توجد طلبات بعد.</div>'}catch(e){alert(e.message)}}
async function setStatus(id,status){try{await api("/admin/orders/"+id,{method:"PATCH",body:JSON.stringify({status})});loadOrders();loadStats()}catch(e){alert(e.message)}}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{filter=b.dataset.status;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadOrders()});
async function loadStats(){const s=await api("/admin/stats");$("#sOrders").textContent=s.orders;$("#sSales").textContent=Number(s.sales).toFixed(2);$("#sAvg").textContent=Number(s.avg).toFixed(2);$("#sPending").textContent=s.pending}
async function loadMenu(){menuData=await api("/admin/menu");$("#menuList").innerHTML=menuData.items.map(i=>`<div class="menuItem"><div class="emoji">${i.image||"🍽️"}</div><div><h3>${esc(i.name)}</h3><p>${esc(i.description||"")}</p><b>${money(i.price)}</b></div><div><input class="editInput" type="number" step="0.01" value="${i.price}" id="price${i.id}"><button class="ghost" onclick="updateItem(${i.id})">حفظ السعر</button></div></div>`).join("")}
async function updateItem(id){const item=menuData.items.find(x=>x.id===id);const price=$("#price"+id).value;await api("/admin/menu/items/"+id,{method:"PUT",body:JSON.stringify({...item,price})});loadMenu()}
$("#addItem").onclick=()=>{$("#itemCat").innerHTML=menuData.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");$("#itemModal").classList.add("show")};
$("#saveItem").onclick=async()=>{await api("/admin/menu/items",{method:"POST",body:JSON.stringify({name:$("#itemName").value,price:$("#itemPrice").value,description:$("#itemDesc").value,category_id:$("#itemCat").value,image:$("#itemEmoji").value})});closeModals();loadMenu()};
async function loadZones(){const z=await api("/admin/zones");$("#zonesList").innerHTML=z.map(x=>`<div class="zone"><b>${esc(x.name)}</b><span><input id="zf${x.id}" value="${x.fee}" type="number" step="0.01"> <button class="ghost" onclick="saveZone(${x.id})">حفظ</button></span></div>`).join("")}
async function saveZone(id){const z=await api("/admin/zones");const x=z.find(a=>a.id===id);x.fee=$("#zf"+id).value;await api("/admin/zones/"+id,{method:"PUT",body:JSON.stringify(x)});loadZones()}
async function loadCoupons(){const c=await api("/admin/coupons");$("#couponsList").innerHTML=c.length?c.map(x=>`<div class="coupon"><b>${esc(x.code)}</b><span>${x.type==="percent"?x.value+"%":money(x.value)}</span><small>حد أدنى ${money(x.min_order)}</small></div>`).join(""):'<div class="panel">لا توجد كوبونات.</div>'}
$("#addCoupon").onclick=()=>$("#couponModal").classList.add("show");
$("#saveCoupon").onclick=async()=>{await api("/admin/coupons",{method:"POST",body:JSON.stringify({code:$("#couponCode").value,type:$("#couponType").value,value:$("#couponValue").value,min_order:$("#couponMin").value,active:true})});closeModals();loadCoupons()};
function closeModals(){document.querySelectorAll(".modal").forEach(x=>x.classList.remove("show"))}
async function loadAll(){await Promise.all([loadStats(),loadOrders()]);setInterval(loadStats,30000);setInterval(loadOrders,30000);setInterval(()=>$("#clock").textContent=new Date().toLocaleTimeString("ar-SA",{hour:"2-digit",minute:"2-digit"}),1000)}
