const state={categories:[],items:[],zones:[],cart:{},cat:"all",coupon:"",couponDiscount:0};
const $=s=>document.querySelector(s), money=n=>(Number(n)||0).toFixed(2)+" ر.س";
async function api(path,opt={}){const r=await fetch("/api"+path,{headers:{"content-type":"application/json",...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"حدث خطأ");return d}
async function boot(){try{const [m,z]=await Promise.all([api("/menu"),api("/zones")]);state.categories=m.categories;state.items=m.items;state.zones=z;renderCats();renderProducts();renderZones();drawCart()}catch(e){console.error(e);$("#products").innerHTML='<div style="grid-column:1/-1;padding:40px;text-align:center">تعذر تحميل المنيو. حاول تحديث الصفحة.</div>'}}
function renderCats(){const all=[{slug:"all",name:"الكل"}];$("#cats").innerHTML=all.concat(state.categories.map(c=>({slug:c.slug,name:c.name}))).map(c=>`<button class="chip ${state.cat===c.slug?"active":""}" data-cat="${c.slug}">${c.name}</button>`).join("");document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;renderCats();renderProducts()})}
function renderProducts(){const q=($("#search")?.value||"").trim().toLowerCase();const arr=state.items.filter(i=>(state.cat==="all"||state.categories.find(c=>c.id===i.category_id)?.slug===state.cat)&&(!q||i.name.toLowerCase().includes(q)));$("#products").innerHTML=arr.length?arr.map(i=>`<article class="product"><div class="productPhoto">${i.image||"🍽️"}</div><h3>${esc(i.name)}</h3><p>${esc(i.description||"من منيو شاكي")}</p><div class="productBottom"><span class="price">${money(i.price)}</span><button class="add" onclick="add(${i.id})">+ إضافة</button></div></article>`).join(""):`<div style="grid-column:1/-1;text-align:center;padding:60px;color:#aaa">لا توجد أصناف مطابقة.</div>`}
function esc(x){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function add(id){state.cart[id]=(state.cart[id]||0)+1;drawCart();openCart()}
function change(id,d){state.cart[id]=(state.cart[id]||0)+d;if(state.cart[id]<=0)delete state.cart[id];drawCart()}
function getLines(){return Object.entries(state.cart).map(([id,qty])=>{const i=state.items.find(x=>x.id==id);return i?{...i,qty}:null}).filter(Boolean)}
function subtotal(){return getLines().reduce((s,i)=>s+i.price*i.qty,0)}
function zoneFee(){const z=state.zones.find(x=>x.id==Number($("#zone")?.value));return z?Number(z.fee):0}
function drawCart(){const lines=getLines();$("#cartBadge").textContent=lines.reduce((s,i)=>s+i.qty,0);$("#cartItems").innerHTML=lines.length?lines.map(i=>`<div class="cartItem"><div class="cartEmoji">${i.image||"🍽️"}</div><div><h4>${esc(i.name)}</h4><small>${money(i.price)}</small></div><div class="qty"><button onclick="change(${i.id},-1)">−</button><b>${i.qty}</b><button onclick="change(${i.id},1)">+</button></div></div>`).join(""):`<div class="empty">السلة فارغة<br><small>أضف اللي تشتهيه وابدأ الطلب.</small></div>`;const sub=subtotal();const del=zoneFee();const total=Math.max(0,sub+del-state.couponDiscount);$("#subtotal").textContent=money(sub);$("#deliveryFee").textContent=$("#zone")?.value?money(del):"اختر المنطقة";$("#total").textContent=money(total);$("#modalTotal").textContent=money(total)}
function renderZones(){$("#zone").innerHTML='<option value="">اختر المنطقة</option>'+state.zones.map(z=>`<option value="${z.id}">${esc(z.name)} — ${money(z.fee)}</option>`).join("");$("#zone").onchange=drawCart}
function openCart(){$("#cartPanel").classList.add("open");$("#shade").classList.add("show")}
function closeCart(){$("#cartPanel").classList.remove("open");$("#shade").classList.remove("show")}
$("#openCart").onclick=openCart;$("#closeCart").onclick=closeCart;$("#shade").onclick=closeCart;$("#startOrder").onclick=()=>{$("#menu").scrollIntoView({behavior:"smooth"});setTimeout(openCart,450)}
$("#search").oninput=renderProducts;
$("#checkout").onclick=()=>{if(!getLines().length)return alert("أضف أصنافًا للسلة أولًا");$("#checkoutModal").classList.add("show");closeCart()}
$("#closeModal").onclick=()=>$("#checkoutModal").classList.remove("show");
$("#applyCoupon").onclick=async()=>{const code=$("#coupon").value.trim().toUpperCase();if(!code){state.coupon="";state.couponDiscount=0;drawCart();return}try{const sub=subtotal();const r=await fetch("/api/check-coupon",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,subtotal:sub})});const d=await r.json();if(!r.ok)throw new Error(d.error||"الكود غير صالح");state.coupon=code;state.couponDiscount=Number(d.discount||0);alert("تم تطبيق الخصم");drawCart()}catch(e){alert(e.message)}};
$("#sendOrder").onclick=async()=>{const msg=$("#formMsg");msg.textContent="جاري إرسال الطلب...";const body={customer:{name:$("#customerName").value,phone:$("#customerPhone").value,address:$("#customerAddress").value},zone_id:Number($("#zone").value)||null,payment_method:$("#payment").value,notes:$("#notes").value,coupon:state.coupon,items:getLines().map(i=>({id:i.id,qty:i.qty}))};try{const d=await api("/orders",{method:"POST",body:JSON.stringify(body)});$("#checkoutModal").classList.remove("show");$("#orderNo").textContent=d.order.order_no;$("#orderTotal").textContent=money(d.order.total);$("#success").classList.add("show");state.cart={};state.coupon="";state.couponDiscount=0;drawCart()}catch(e){msg.textContent=e.message}};
$("#done").onclick=()=>$("#success").classList.remove("show");
boot();
